= Installation

You can get the `metanorma` command-line executable by installing this Ruby gem.

[IMPORTANT]
====
To install the Metanorma toolchain we recommend to use one of the ways described in
https://www.metanorma.com/author/topics/install/[Metanorma installation] topic.
Installing this gem by hand may not be the easiest way.

When following this installation method, to start building documents you may have to take care
of manually installing some required third-party software as well.
Which exactly depends on what documents you’re building, below notes cover some of that.
====


== Installing the Metanorma CLI gem

[source,console]
----
gem install metanorma-cli
----

Installing the gem will also install all officially supported Metanorma flavors
(such as ISO, CalConnect, IETF, etc).


== Dependencies

=== Puppeteer

*If you are going to generate PDFs from HTML* (which applies to CalConnect Standard Documents),
you will also need to install the https://github.com/GoogleChrome/puppeteer[Puppeteer] Node library.

* Ensure you have Node of at least version 7.6.0:
** https://nodejs.org/en/download/
** On macOS you should be able to `brew install node`
* Ensure you have NPM: https://docs.npmjs.com/getting-started/installing-node
* Install Puppeteer globally in your system: `npm install -g --save --save-exact puppeteer`

=== PlantUML

*If your documents include link:/author/topics/document-format/diagrams/[PlantUML diagrams]*,
PlantUML will have to be installed.

* `brew install plantuml` on MacOS.
* For Linux, link the PlantUML jar file into a command line executable; see
`.travis.yml` for an example.

If PlantUML is not installed locally, the source PlantUML is incorporated into
the output document as sourcecode.


== Installation notes for Windows

To be able to compile gem with a native extension you must have `RIDK` installed.
If you are installing metanorma with chocolatey installation script will do this for you
