= Installation

You can get the `metanorma` command-line executable by installing this `Ruby` gem.

[IMPORTANT]
====
To install the Metanorma toolchain we recommend using one of the ways described in
https://www.metanorma.com/author/topics/install/[Metanorma installation] topic.
Installing this gem by hand may not be the easiest way.

When following this installation method, to start building documents you may have to take care
of manually installing some required third-party software as well.
This exactly depends on what documents you’re building, below notes cover some of that.
====


== Install Ruby

== macOS

Ruby already pre-installed, but it's may be outdated. So recommended to install it from https://brew.sh/[`brew`]

[source,console]
----
xcode-select —install
brew install rbenv
rbenv install 2.7.4
----

== Linux

Ruby maybe not pre-installed on your Linux distribution, https://www.ruby-lang.org/en/documentation/installation[follow the official guide] to install it

== Windows

Ruby is not pre-installed on Windows in comparison to macOS and most Linux

Probably the easiest way to install it with `RubyInstaller` (as described in https://www.ruby-lang.org/en/documentation/installation[the official guide])

If you need some automated way to install, we recommend using https://chocolatey.org/install[chocolatey] and commands below:

[source,console]
----
choco install -y msys2 ruby
refreshenv
ridk install 3
----

Those commands will work with PowerShell and CMD

== Other

If you have some issues with Ruby installation checkout https://www.ruby-lang.org/en/documentation/installation[the official guide]


== Installing the Metanorma CLI gem

Once Ruby is installed, you can get metanorma

[source,console]
----
gem install metanorma-cli
----

Installing the gem will also install all officially supported Metanorma flavors
(such as ISO, CalConnect, IETF, etc).


== Dependencies

=== Java

You will have to have a Java runtime installed. Use

* `brew cask install java` - on macOS
* Linux is diverse, you can follow https://www.java.com/en/download/help/linux_install.html[the official instructions]
* `choco install -y javaruntime` - on Windows

=== PlantUML

*If your documents include link:/author/topics/document-format/diagrams/[PlantUML diagrams]*,
PlantUML will have to be installed.

* `brew install plantuml` on MacOS.
* For Linux, link the PlantUML jar file into a command line executable; see
`.travis.yml` for an example.
* `choco install -y plantuml`

If PlantUML is not installed locally, the source PlantUML is incorporated into
the output document as sourcecode.

=== Graphviz

Needed by `LutaML` to draw diagrams

* `brew install graphviz` - on macOS
* `choco install -y graphviz` - on Windows

For Linux use https://graphviz.org/download/#linux[available packages] (`apt` or `yum`)

=== xml2rfc

`xml2rfc` is Python's package which required for `IETF`

To install python:

* `brew install python3` - on macOS
* `choco install -y python` - on Windows

Then install `xml2rfc` with:

[source,console]
----
pip3 install xml2rfc
----

=== Inkscape

Optional dependency. Inkscape is needed for `SVG` to `EMF` functionality. 

* `brew install inkscape` - on macOS
* `choco install -y python` - on Windows
* https://inkscape.org/release/[Linux instructions]

=== LaTeXML

Optional dependency. `LaTeXML` is needed for Metanorma for LaTeX functionality.

Most of the packages from various package manager listed on https://dlmf.nist.gov/LaTeXML/get.html are outdated

Originally `LaTeXML` is a `perl` module so more reliable way to install it with https://metacpan.org/dist/App-cpanminus/view/bin/cpanm[`cpanm` package manager]

[source,console]
----
curl -L https://cpanmin.us | perl - --sudo App::cpanminus
cpanm --notest LaTeXML
# or
cpanm --notest git://github.com/brucemiller/LaTeXML.git@9a0e7dc5
----

But it also can be installed with (but always check the version, because it may be outdated):
* `snap install latexml` - on Linux
* `choco install -y latexml` - on Windows
* `brew install latexml` - on macOS
