= Installation

The `metanorma` command-line executable gets installed via a Ruby gem.
Depending on your use case, you may need to install Puppeteer Node package.

[TIP]
====
To use Metanorma, normally *you don’t manually install this gem*.
There are quicker ways of getting Metanorma up and running, including via Docker.
Please refer to https://www.metanorma.com/docs/getting-started/[Getting Started] instead.

The instructions here are only relevant if you want to manually install
Metanorma via Rubygems for some specific reason.
====


== Installing the Metanorma CLI gem

[source,console]
----
gem install metanorma-cli
----

Installing the gem will also install all officially supported Metanorma flavors
(such as ISO, CalConnect, IETF, etc).


== Installing Puppeteer

If you are going to generate PDFs from HTML (which applies to CalConnect Standard Documents),
you will also need to install the https://github.com/GoogleChrome/puppeteer[Puppeteer] Node library:

* Ensure you have Node at least 7.6.0:
** https://nodejs.org/en/download/
** On macOS you should be able to `brew install node`
* Ensure you have NPM: https://docs.npmjs.com/getting-started/installing-node
* Install Puppeteer globally in your system: `npm install -g --save --save-exact puppeteer`


== Installation notes for Windows

=== Background

The Metanorma toolchain (i.e. when you install `metanorma-cli`)
is dependent on https://github.com/glejeune/ruby-xslt[`ruby-xslt`].

And `ruby-xslt` in its turn depends on the native libraries: `libxml2` and `libxslt`.

On Linux and macOS this is generally not a problem, as these native libraries
are already present, or could be easily installed using package managers:

* Linux: `yum` on CentOS, `apt` on Debian/Ubuntu, `dnf` on Fedora
* macOS: https://brew.sh[Homebrew]

However, on Windows it gets a bit tricky.

To satisfy this dependency on Windows, you need to:

. Get native libraries (`libxml2` and `libxslt`) compiled for your architecture (`x86` for 32-bit or `x64` for 64-bit Windows)
. Provide right options during gem build
. Ensure these native libraries are accessible at run-time (of the Metanorma toolchain)

=== Installing the native libraries (prerequisites)

Here we have two option:

* Build from source code (difficult)
* Get pre-built binaries (easy)

We go with the latter because it is faster and less error-prone.

The pre-built binaries can be installed via the https://chocolatey.org/[Chocolatey] package manager on Windows.

. Installing Chocolatey is straightforward: follow instructions at https://chocolatey.org/install

. Then, both `libxml2` and `libxslt` can be installed by running this command
[source,sh]
----
cinst xsltproc
----

Once this is done, the necessary libraries/headers are installed in the
`%ChocolateyInstall%\lib\xsltproc\dist` directory.


=== Installing the Metanorma gems

Here there are also two options:

* Using the `gem` command
* Using the `bundle` command

NOTE: Before running this step you must have already installed the prerequisite libraries stated above.


==== Installing the gem manually via `gem`

The commands are given below.

[source,sh]
----
gem install ruby-xslt -- ^
	--with-xml2-include=%ChocolateyInstall%\lib\xsltproc\dist\include\libxml2 ^
	--with-xslt-include=%ChocolateyInstall%\lib\xsltproc\dist\include ^
	--with-xml2-lib=%ChocolateyInstall%\lib\xsltproc\dist\lib ^
	--with-xslt-lib=%ChocolateyInstall%\lib\xsltproc\dist\lib
----

==== Installing the gem via `bundle`

NOTE: Before running this step you must have already installed the prerequisite libraries stated above.

[source,sh]
----
bundle config build.ruby-xslt ^
	--with-xml2-include=%ChocolateyInstall%\lib\xsltproc\dist\include\libxml2 ^
	--with-xslt-include=%ChocolateyInstall%\lib\xsltproc\dist\include ^
	--with-xml2-lib=%ChocolateyInstall%\lib\xsltproc\dist\lib ^
	--with-xslt-lib=%ChocolateyInstall%\lib\xsltproc\dist\lib
bundle install
----


==== Success message

With both methods of installing the gem, you should see the following output without any errors.

[source]
----
Fetching ruby-xslt X.X.XX
Installing ruby-xslt X.X.XX with native extensions
----



=== Ensuring the native libraries are available at run-time


==== Step 1: General

Firstly, the `ruby-xslt` gem expects the names of `libxml2` and `libxslt` library files to
not have the version numbers in filenames.

We need to '`strip`' away the version numbers from the DLL files using the following commands:

[source,sh]
----
xcopy /y %ChocolateyInstall%\lib\xsltproc\dist\bin\libxml2*.dll %ChocolateyInstall%\lib\xsltproc\dist\bin\libxml2.dll*
xcopy /y %ChocolateyInstall%\lib\xsltproc\dist\bin\libxslt*.dll %ChocolateyInstall%\lib\xsltproc\dist\bin\libxslt.dll*
xcopy /y %ChocolateyInstall%\lib\xsltproc\dist\bin\libexslt*.dll %ChocolateyInstall%\lib\xsltproc\dist\bin\libexslt.dll*
----


==== Step 2: If Ruby version >= 2.4.1

In Ruby versions newer than 2.4.1, we can use https://github.com/oneclick/rubyinstaller2/wiki/For-gem-developers#environment-variable-ruby_dll_path[`RUBY_DLL_PATH` environment variable]
to set the correct Ruby DLL path.

This can be accomplished this by running the following one-time command in PowerShell or `cmd`:

[source,sh]
----
setx /m RUBY_DLL_PATH "%ChocolateyInstall%\lib\xsltproc\dist\bin;%RUBY_DLL_PATH%"
----

NOTE: The `setx` command stores this change in the registry and therefore the
configuration will persist upon restarts.


==== Step 2: If Ruby version < 2.4.1

Prior to Ruby 2.4.1, the native libraries must be copied to the Ruby `bin` directory to be
available for the Ruby runtime as follows (in PowerShell or `cmd`):

[source]
----
xcopy /y %ChocolateyInstall%\lib\xsltproc\dist\bin\lib*.dll C:\Ruby25\bin*
----

NOTE: This is also a one-time change that persists across restarts.


=== Installation completed!

If you got here following the instructions step by step, you have setup
Metanorma on Windows successfully.

Congratulations!!!


