name: fonts-check

on:
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:
  pull_request:

permissions:
  contents: write

jobs:
  prepare:
    uses: metanorma/ci/.github/workflows/prepare-rake.yml@main

  list-flavors:
    runs-on: ubuntu-latest
    outputs:
      flavors: ${{ steps.result.outputs.list }}
    steps:
      - uses: actions/checkout@v4

      - id: result
        run: |
          cat .github/workflows/samples-smoke-matrix.json | jq -r '.flavor[].id' | sed '/-private$/d' | jq -R -s -c 'split("\n") | map(select(length > 0))' > flavors.json
          cat flavors.json
          echo "list=$(cat flavors.json tr '\n' ' ')" >> $GITHUB_OUTPUT

  test-flavor-fonts:
    name: Test fonts for ${{ matrix.flavor }}
    runs-on: ubuntu-latest
    needs: [prepare, list-flavors]

    concurrency:
      group: 'fonts-check-${{ matrix.flavor }}'
      cancel-in-progress: true

    continue-on-error: true

    strategy:
      max-parallel: 5
      fail-fast: false
      matrix:
        flavor: ${{ fromJson(needs.list-flavors.outputs.flavors) }}

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ needs.prepare.outputs.default-ruby-version }}
        bundler-cache: true

    - run: bundle exec bin/font-test ${{ matrix.flavor }}
