name: integration-tests

on:
  repository_dispatch:
    types: [ tests-passed, release-passed ]

jobs:
  build-matrices:
    runs-on: ubuntu-latest
    outputs:
      samples-matrix: ${{ steps.build-samples-matrix.outputs.matrix }}
      templates-matrix: ${{ steps.build-templates-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
      - id: build-samples-matrix
        run: echo "matrix=$(cat .github/workflows/samples-matrix.json | tr '\n' ' ')" >> $GITHUB_OUTPUT
      - id: build-templates-matrix
        run: echo "matrix=$(cat .github/workflows/templates-smoke-matrix.json | tr '\n' ' ')" >> $GITHUB_OUTPUT

  test-samples:
    name: Test samples-${{ matrix.flavor.id }} ${{ matrix.ruby.version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build-matrices

    concurrency:
      group: '${{ github.workflow }}-${{ github.job }}-${{ matrix.ruby.version }}-${{ matrix.flavor.id }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true

    continue-on-error: ${{ matrix.flavor.experimental || matrix.ruby.experimental }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrices.outputs.samples-matrix) }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: metanorma/ci/gh-rubygems-setup-action@main
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby.version }}
        rubygems: ${{ matrix.ruby.rubygems }}
        bundler-cache: true

    - uses: actions/checkout@v3
      with:
        submodules: recursive
        repository: metanorma/mn-samples-${{ matrix.flavor.id }}
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
        path: samples
        fetch-depth: 1

    - run: |
        bundle remove metanorma-cli
        bundle add metanorma-cli --path ..
      working-directory: samples

    - uses: actions-mn/site-gen@v1
      with:
        source-path: samples
        agree-to-terms: true
        use-bundler: true

  test-templates:
    name: Test templates-${{ matrix.flavor.id }} ${{ matrix.ruby.version }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    needs: build-matrices

    concurrency:
      group: '${{ github.workflow }}-${{ github.job }}-${{ matrix.ruby.version }}-${{ matrix.flavor.id }}-${{ github.head_ref || github.ref_name }}'
      cancel-in-progress: true

    continue-on-error: ${{ matrix.flavor.experimental || matrix.ruby.experimental }}
    strategy:
      max-parallel: 5
      fail-fast: false
      matrix: ${{ fromJson(needs.build-matrices.outputs.templates-matrix) }}

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true

    - uses: metanorma/ci/gh-rubygems-setup-action@main
      with:
        token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby.version }}
        rubygems: ${{ matrix.ruby.rubygems }}
        bundler-cache: true

    - uses: actions-mn/cli/new@main
      with:
        type: ${{ matrix.flavor.id }}
        doctype: ${{ matrix.flavor.type }}
        output-path: template
        template: https://github.com/metanorma/mn-templates-${{ matrix.flavor.id }}
        overwrite: true
        use-bundler: true

    - run: |
        bundle remove metanorma-cli
        bundle add metanorma-cli --path ..
      working-directory: template

    - uses: actions-mn/site-gen@v1
      with:
        source-path: template
        agree-to-terms: true
        use-bundler: true
