name: notify

on:
  push:
    branches: [ master ]
    tags:
      - '*'

jobs:
  notify:
    name: Notify dependent repos
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repositories
        env:
          GH_USERNAME: metanorma-ci
          GH_ACCESS_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
        run: |
          curl -LO --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/trigger-gh-actions.sh
          [[ -f ".github/workflows/dependent_repos.env" ]] && source .github/workflows/dependent_repos.env
          CLIENT_PAYLOAD=$(cat <<EOF
          "{ "ref": "${GITHUB_REF}", "repo": "${GITHUB_REPOSITORY}" }"
          EOF
          )
          for repo in $TEMPLATE_REPOS" $SAMPLES_REPOS"
          do
            sh trigger-gh-actions.sh $ORGANISATION $repo $GH_USERNAME $GH_ACCESS_TOKEN $GITHUB_REPOSITORY "$CLIENT_PAYLOAD"
          done

      - name: Trigger release repositories
        if: github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags/v')
        env:
          GH_USERNAME: metanorma-ci
          GH_ACCESS_TOKEN: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
        run: |
          curl -LO --retry 3 https://raw.githubusercontent.com/metanorma/metanorma-build-scripts/master/trigger-gh-actions.sh
          [[ -f ".github/workflows/dependent_repos.env" ]] && source .github/workflows/dependent_repos.env
          CLIENT_PAYLOAD=$(cat <<EOF
          "{ "ref": "${GITHUB_REF}", "repo": "${GITHUB_REPOSITORY}" }"
          EOF
          )
          for repo in $DEPENDENT_REPOS
          do
            sh trigger-gh-actions.sh $ORGANISATION $repo $GH_USERNAME $GH_ACCESS_TOKEN $GITHUB_REPOSITORY "$CLIENT_PAYLOAD"
          done