name: rake

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:
  workflow_dispatch:

jobs:
  rake:
    uses: metanorma/ci/.github/workflows/mn-processor-rake.yml@main
    with:
      samples-matrix-json-file: .github/workflows/samples-smoke-matrix.json
      templates-matrix-json-file: .github/workflows/templates-smoke-matrix.json
    secrets:
      pat_token: ${{ secrets.METANORMA_CI_PAT_TOKEN }}
